server: 
  port: 136
 # ssl:
 #   key-store: C:/Program Files/Java/jdk1.8.0_151/jre/lib/security/cacerts
 #   key-store-password: changeit
 #   key-password: Reid.Zac36
 
logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.virkade: DEBUG
    org.hibernate: ERROR
  file: virkade-cms-app.log
   
security:
  basic:
    enabled: false

    
    
#Port: 465 (SSL required) or 587 (TLS required)   
    